name: Run unit tests on PR for CI

on:
  pull_request_target:
    branches: [ develop, main ]

jobs:
    test:
        name: Test
        
        runs-on: macos-12
        
        steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Select Xcode Version
          uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: '13.4.0'

        - name: Run tests
          run: xcodebuild test -scheme EazelAnimationsKitTests -destination 'platform=iOS Simulator,OS=15.5,name=iPhone 11'
